CXX=clang++
CXXFLAGS=-g -std=c++11 -Wall -pedantic

borah : borah.cpp circuit.cpp helper.cpp main.cpp net.cpp point.cpp imageIO.cpp
	g++ -std=c++11 -o borah.out borah.cpp circuit.cpp helper.cpp main.cpp net.cpp point.cpp imageIO.cpp


